#include <asm/arch/hardware.h>
#include <asm/io.h>
#include <div64.h>
#include <exports.h>

#define TRIG        (1 << 4)    // PA4

void do_ping(void)
{
    /* set TRIG to HIGH for 10 μs to send out an eight cycle sonic burst at 40 kHZ */
    setbits(8, PPI_PA, TRIG);
    udelay(10);
    clrbits(8, PPI_PA, TRIG);
    out_8(CT_CNTR1, 0);
    out_8(CT_CNTR1, 0);

    /* after a sonic burst has been sent the ECHO pin will go HIGH
       until an ultrasonic burst is detected back */
    udelay(8824);       /* 2 * 1500mm / 340m/s */

    /* read back the Timer1 values */
    out_8(CT_CWR, CT_CWR_SC1);
    int lsb = in_8(CT_CNTR1), msb = in_8(CT_CNTR1);
    /* The code generated by the modern toolchain seems having issues while
       compiling the number divisions for the ARM7DI based LH77790 */
    unsigned distance = (65536 - (msb << 8 | lsb));
    uint64_t d = distance;
    d *= 4 * 172;
    do_div(d, 100000);
    printf("Distance: %d mm\n", (uint)d);
}

#define KEY_SPACE   0x20
#define KEY_ESC     0x1b

int main(int argc, char *const argv[])
{
    app_startup(argv);

    /* set Group A & B in mode 0, PA[0:7] and PC[4:7] as outputs, others remains as inputs */
    out_8(PPI_CTLR, PPI_CTLR_MODE |
                    PPI_CTLR_PA_MODE0 |
                    PPI_CTLR_PB_MODE0 | PPI_CTLR_PB_IN |
                    PPI_CTLR_PCL_IN);
    clrbits(8, PPI_PA, TRIG);

    /* run the Timer1 in 25MHz and count the ECHO duration by CTGATE1 */
    out_32(CT1CCR, 1 << 0);
    clrbits(32, IOCR, IOCR_CT1G_HI);
    out_8(CT_CWR, CT_CWR_SC1 | CT_CWR_WORD | CT_CWR_MODE0);

    printf ("Hit Space to ping, and ESC to exit ...\n");
    bool running = true;
    while (running) {
        while (!tstc());
        switch (getc()) {
            case KEY_SPACE:
                do_ping();
                break;
            case KEY_ESC:
                running = false;
        }
    }

    return 0;
}
